name: Promotion Testing

on:
  workflow_dispatch:

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: vars
        run: echo "$(cat version/VERSION)" >> $VERSION
      - name: Promote
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$VERSION"
