name: Promotion Testing

on:
  workflow_dispatch:

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: vars
        run: echo "VERSION=$(cat version/VERSION)" >> $GITHUB_OUTPUT
      - name: Validate Branch Name
        env:
          BRANCH: ${{ github.ref_name }}
          VERSION: ${{ steps.vars.outputs.version }}
          EXPECTED: ${{ format('{0}{1}', 'release/v', steps.vars.outputs.version) }}
        if: ${{ $BRANCH != $EXPECTED }}
        run: |
            echo Improper branch name: $BRANCH
            echo Expected branch name: $EXPECTED
            exit 1
      - name: Promote
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          VERSION: ${{ steps.vars.outputs.version }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$VERSION"
