name: Promotion Testing

on:
  workflow_dispatch:

jobs:
  check-user:
    name: Validate Team
    runs-on: ubuntu-latest
    steps:
      - name: Check user permissions
        uses: tspascoal/get-user-teams-membership@v2
        id: teamAffiliation
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          username: ${{ github.actor }}
          team: team-team
      - name: Debug Output
        env:
          output: ${{ steps.teamAffiliation.outputs.isTeamMember }}
        run: echo $output
      - name: Abort workflow
        if: ${{ steps.teamAffiliation.outputs.isTeamMember == 'false' }}
        run: |
          echo "You do not have permission to run this workflow. Only members of the GitHub team <TODO> may run this workflow."
          exit 1
  staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: vars
        run: echo "VERSION=$(cat version/VERSION)" >> $GITHUB_OUTPUT      
      - name: Validate Branch Name
        env:
          BRANCH: ${{ github.ref_name }}
          VERSION: ${{ steps.vars.outputs.version }}
          EXPECTED: ${{ format('{0}{1}', 'release/v', steps.vars.outputs.version) }}
        if: ${{ env.BRANCH != env.EXPECTED }}
        run: |
            echo Improper branch name: $BRANCH
            echo Expected branch name: $EXPECTED
            exit 1
      - name: Promote
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          VERSION: ${{ steps.vars.outputs.version }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$VERSION"
