name: Promotion Testing

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        type: choice
        default: main
        options:
          - main
          - pre-release

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Promote
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
