name: Promotion Testing

on:
  workflow_dispatch:

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: vars
        run: echo "VERSION=$(cat version/VERSION)" >> $GITHUB_OUTPUT
      - name: Validate Branch Name
        env:
          branchName: ${{ github.ref_name }}
        run: |
          expectedBranchName=$("releases/v" + $VERSION)
          if ["$expectedBranchName" != "$branchName"]; then
            echo "Improper branch name: " + $branchName
            echo "Expected branch name: releases/v" + $VERSION
            exit 1
          fi
      - name: Promote
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          VERSION: ${{ steps.vars.outputs.version }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$VERSION"
