name: Promotion Testing

on:
  workflow_dispatch:

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Promote
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          VERSION: ${{ cat version/VERSION }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$VERSION"
